apiVersion: v1
kind: Deployment
metadata:
  name: sample
  labels:
    app.kubernetes.io/name: sample
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample
    spec:
      containers:
      - name: app
        image: rails:xxxxx
